# Generated by Django 2.2.3 on 2019-07-10 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Question Text')),
                ('dimention', models.CharField(help_text='Dimention', max_length=2)),
                ('direction', models.IntegerField(help_text='Direction')),
                ('meaning', models.CharField(help_text='Meaning', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Worker Email', max_length=254)),
                ('answer1', models.IntegerField(help_text='You find it takes effort to introduce yourself to other people.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('answer2', models.IntegerField(help_text='You consider yourself more practical than creative.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('answer3', models.IntegerField(help_text='Winning a debate matters less to you than making sure no one gets upset.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('answer4', models.IntegerField(help_text='You get energized going to social events that involve many interactions.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('answer5', models.IntegerField(help_text='You often spend time exploring unrealistic and impractical yet intriguing ideas.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('answer6', models.IntegerField(help_text='Deadlines seem to you to be of relative rather than absolute importance.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('answer7', models.IntegerField(help_text='Logic is usually more important than heart when it comes to making important decisions.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('answer8', models.IntegerField(help_text='Your home and work environments are quite tidy.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('answer9', models.IntegerField(help_text='You do not mind being at the center of attention.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('answer10', models.IntegerField(help_text='Keeping your options open is more important than having a to-do list.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('result', models.CharField(help_text='Result', max_length=4)),
            ],
        ),
    ]
